### ISSUE TITLE
Return format of Status Node, enhancement

### ISSUE THREAD

**Issue by Rolf-M** [originallyus/node-red-contrib-better-sonos#8]
It would be nicer to have all the status within the msg.payload
Right now, only the current track is returned in payload. This is not so nice if you want to use the other information for further processing. Payload can carry a complete object, so it would be nicer to have everything in there

**Comment by torinnguyen** [comment]
It is a design choice I've made. There is no right or wrong in this case. It is a choice between convenience or functionality.
I chose this format so that the track title can be fed directly into other nodes such as TTS, MQTT, chatbot message so that less savvy users would be able to directly hook it up to another node.
If you are power user, you'd know how to use a function node to extract the info you need.
